In [1]:
import pandas as pd
import numpy as np

In [2]:
file_data = pd.read_csv("C:/Users/kiran/Documents/Data_science_final_project/dataset_final.csv")

In [22]:
file_data.head()

problem_id  level_type  attempts_range  submission_count  problem_solved  \
0   prob_918           5               1                84              73   
1  prob_2990           6               1                84              73   
2  prob_1358           4               1                84              73   
3  prob_4278           1               1                84              73   
4  prob_1868           1               2                84              73   

   contribution  follower_count   rating  rank  
0            10             120  499.713     0  
1            10             120  499.713     0  
2            10             120  499.713     0  
3            10             120  499.713     0  
4            10             120  499.713     0

In [4]:
file_data = file_data.drop(["user_id","max_rating"],axis=1)

In [8]:
file_data = file_data.drop(["country"],axis=1)

In [23]:
file_data = file_data.drop(["problem_id"],axis=1)

In [5]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
enc.fit(file_data['level_type'])
file_data['level_type'] = enc.transform(file_data['level_type'])

In [9]:
enc.fit(file_data['rank'])
file_data['rank'] = enc.transform(file_data['rank'])

In [24]:
df = file_data
df_attempt = df["attempts_range"]
df = df.drop("attempts_range",axis=1)
df.insert(0,"attempts_range",df_attempt)

In [25]:
X = df.iloc[:,1:]
y = df.iloc[:,:1]

In [18]:
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0)

In [48]:
test = X_train[24:25]

In [49]:
test

level_type  submission_count  problem_solved  contribution  \
117961           2               110             100             0   

        follower_count   rating  rank  
117961               7  492.833     0

In [50]:
y_train[24:25]

attempts_range
117961               1

In [15]:
from sklearn.svm import SVC 

In [16]:
model = SVC()

In [27]:
model.fit(X_train,y_train)

C:\Users\kiran\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\kiran\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [52]:
import pickle

In [53]:
pkl_filename = "pickle_model.pkl"
with open(pkl_filename, 'wb') as file:
   pickle.dump(model, file)

In [54]:
with open(pkl_filename, 'rb') as file:
   pickle_model = pickle.load(file)

In [55]:
pickle.load(open(pkl_filename,'rb'))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [56]:
pickle_model.predict(test)

array([2], dtype=int64)

In [30]:
y_pred = model.predict(X_test)

In [34]:
y_pred[100:200]

array([3, 1, 1, 3, 1, 2, 1, 4, 1, 1, 2, 3, 1, 3, 6, 1, 2, 1, 4, 3, 3, 6,
       1, 1, 1, 6, 1, 1, 1, 1, 3, 1, 1, 5, 1, 6, 1, 1, 1, 1, 4, 2, 1, 2,
       2, 1, 2, 4, 2, 6, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 1, 2, 4, 6,
       3, 2, 1, 2, 1, 2, 1, 4, 1, 1, 2, 1, 2, 2, 2, 1, 5, 5, 5, 6, 2, 5,
       2, 2, 4, 2, 4, 1, 2, 2, 1, 3, 1, 1], dtype=int64)

In [35]:
y_test[100:200]

attempts_range
59598                5
60443                2
133177               1
127062               5
140453               2
57248                5
38777                1
45451                4
78308                1
57399                1
92567                6
113807               2
95445                2
88388                2
65076                3
23355                1
69215                1
34339                3
48215                6
9679                 2
46543                2
148346               4
148477               1
49229                1
67556                1
114681               5
38844                1
124299               4
36366                1
91827                1
...                ...
634                  1
102328               5
155021               1
115117               6
24342                2
139509               2
71740                2
47029                3
132389               6
121721               2
69975                3
130662               2
148392               5
24446                5
144927               6
135267               3
91060                3
41537                4
78208                3
8301                 3
20630                2
85120                1
126344               5
143314               2
64411                4
125394               1
153140               1
31757                4
70250                1
48613                2

[100 rows x 1 columns]

In [33]:
model.score(X_test,y_test)

0.41744797032763237

In [51]:
model.predict(test)

array([2], dtype=int64)

In [43]:
np.unique(y_pred)

array([1, 2, 3, 4, 5, 6], dtype=int64)